class TestData:
    def __init__(self):
        self.short_test_data = [
            {
                "role_name": "Teleportation Engineer",
                "event_type": "SciFi",
                "age_min": "21",
                "age_exception_allowed": "FALSE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "FALSE",
                "required_experience": "TRUE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "FALSE",
                "physical_req": "FALSE",
                "time_commitment": "2 days",
                "game_category": "Quantum",
                "interest_category": "Engineering",
                "notes": "Must understand quantum entanglement"
            },
            {
                "role_name": "Dragon Handler",
                "event_type": "Fantasy",
                "age_min": "18",
                "age_exception_allowed": "TRUE",
                "required_certifications": "FALSE",
                "post_high_school": "FALSE",
                "required_skills": "TRUE",
                "prior_first_exp": "TRUE",
                "required_experience": "FALSE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "TRUE",
                "physical_req": "TRUE",
                "time_commitment": "1.5 days",
                "game_category": "Creature",
                "interest_category": "Adventure",
                "notes": "Fireproof clothing provided"
            },
            {
                "role_name": "Galactic Translator",
                "event_type": "Interstellar",
                "age_min": "20",
                "age_exception_allowed": "FALSE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "TRUE",
                "required_experience": "TRUE",
                "preferred_experience": "FALSE",
                "basic_game_knowledge": "FALSE",
                "physical_req": "FALSE",
                "time_commitment": "3 days",
                "game_category": "Communication",
                "interest_category": "Linguistics",
                "notes": "Must speak at least 3 alien dialects"
            },
        ]

        self.medium_test_data = [
            {
                "role_name": "Teleportation Engineer",
                "event_type": "SciFi",
                "age_min": "21",
                "age_exception_allowed": "FALSE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "FALSE",
                "required_experience": "TRUE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "FALSE",
                "physical_req": "FALSE",
                "time_commitment": "2 days",
                "game_category": "Quantum",
                "interest_category": "Engineering",
                "notes": "Must understand quantum entanglement"
            },
            {
                "role_name": "Dragon Handler",
                "event_type": "Fantasy",
                "age_min": "18",
                "age_exception_allowed": "TRUE",
                "required_certifications": "FALSE",
                "post_high_school": "FALSE",
                "required_skills": "TRUE",
                "prior_first_exp": "TRUE",
                "required_experience": "FALSE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "TRUE",
                "physical_req": "TRUE",
                "time_commitment": "1.5 days",
                "game_category": "Creature",
                "interest_category": "Adventure",
                "notes": "Fireproof clothing provided"
            },
            {
                "role_name": "Galactic Translator",
                "event_type": "Interstellar",
                "age_min": "20",
                "age_exception_allowed": "FALSE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "TRUE",
                "required_experience": "TRUE",
                "preferred_experience": "FALSE",
                "basic_game_knowledge": "FALSE",
                "physical_req": "FALSE",
                "time_commitment": "3 days",
                "game_category": "Communication",
                "interest_category": "Linguistics",
                "notes": "Must speak at least 3 alien dialects"
            },
            {
                "role_name": "Potion Quality Inspector",
                "event_type": "Fantasy",
                "age_min": "22",
                "age_exception_allowed": "FALSE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "FALSE",
                "prior_first_exp": "FALSE",
                "required_experience": "FALSE",
                "preferred_experience": "FALSE",
                "basic_game_knowledge": "TRUE",
                "physical_req": "FALSE",
                "time_commitment": "1 day",
                "game_category": "Alchemy",
                "interest_category": "Science",
                "notes": "Beware of smoke and odd smells"
            },
            {
                "role_name": "Virtual Arena Referee",
                "event_type": "eSports",
                "age_min": "16",
                "age_exception_allowed": "TRUE",
                "required_certifications": "FALSE",
                "post_high_school": "FALSE",
                "required_skills": "TRUE",
                "prior_first_exp": "FALSE",
                "required_experience": "FALSE",
                "preferred_experience": "FALSE",
                "basic_game_knowledge": "TRUE",
                "physical_req": "FALSE",
                "time_commitment": "6 hours",
                "game_category": "Combat",
                "interest_category": "Gaming",
                "notes": ""
            },
            {
                "role_name": "Magical Ethics Officer",
                "event_type": "Fantasy",
                "age_min": "25",
                "age_exception_allowed": "FALSE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "TRUE",
                "required_experience": "TRUE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "FALSE",
                "physical_req": "FALSE",
                "time_commitment": "2.5 days",
                "game_category": "Legal",
                "interest_category": "Philosophy",
                "notes": "Background check required"
            },
            {
                "role_name": "Wand Charging Technician",
                "event_type": "MagicTech",
                "age_min": "17",
                "age_exception_allowed": "TRUE",
                "required_certifications": "FALSE",
                "post_high_school": "FALSE",
                "required_skills": "TRUE",
                "prior_first_exp": "FALSE",
                "required_experience": "FALSE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "TRUE",
                "physical_req": "TRUE",
                "time_commitment": "0.5 days",
                "game_category": "Maintenance",
                "interest_category": "Technical",
                "notes": ""
            },
            {
                "role_name": "Space Map Navigator",
                "event_type": "SciFi",
                "age_min": "19",
                "age_exception_allowed": "TRUE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "FALSE",
                "required_experience": "FALSE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "TRUE",
                "physical_req": "FALSE",
                "time_commitment": "4 hours",
                "game_category": "Navigation",
                "interest_category": "Exploration",
                "notes": "Must understand stellar coordinates"
            },
            {
                "role_name": "Historical Reenactment Coordinator",
                "event_type": "History",
                "age_min": "20",
                "age_exception_allowed": "TRUE",
                "required_certifications": "FALSE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "TRUE",
                "required_experience": "FALSE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "TRUE",
                "physical_req": "TRUE",
                "time_commitment": "2 days",
                "game_category": "Drama",
                "interest_category": "Storytelling",
                "notes": "Some costume handling required"
            },
            {
                "role_name": "Time Travel Safety Officer",
                "event_type": "Temporal",
                "age_min": "26",
                "age_exception_allowed": "FALSE",
                "required_certifications": "TRUE",
                "post_high_school": "TRUE",
                "required_skills": "TRUE",
                "prior_first_exp": "TRUE",
                "required_experience": "TRUE",
                "preferred_experience": "TRUE",
                "basic_game_knowledge": "FALSE",
                "physical_req": "TRUE",
                "time_commitment": "3.5 days",
                "game_category": "Risk",
                "interest_category": "Security",
                "notes": "Must resist paradoxes under pressure"
            }
        ]

